cn3.hpc.itu.dk
Lmod has detected the following error: The following module(s) are unknown:
"cuda"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "cuda"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/run.py", line 676, in determine_local_world_size
    return int(nproc_per_node)
           ^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ccor/.conda/envs/counter/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/run.py", line 908, in run
    config, cmd, cmd_args = config_from_args(args)
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/run.py", line 789, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/run.py", line 705, in determine_local_world_size
    raise ValueError(
ValueError: Unsupported nproc_per_node value: 
