cn11.hpc.itu.dk
/var/spool/slurmd/job03452/slurm_script: line 17: cd: /ResearchProject: No such file or directory
W1127 23:09:18.989000 140218904396800 torch/distributed/run.py:779] 
W1127 23:09:18.989000 140218904396800 torch/distributed/run.py:779] *****************************************
W1127 23:09:18.989000 140218904396800 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1127 23:09:18.989000 140218904396800 torch/distributed/run.py:779] *****************************************
/home/ccor/.conda/envs/captum_test/bin/python: can't open file '/home/ccor/train.py': [Errno 2] No such file or directory
/home/ccor/.conda/envs/captum_test/bin/python: can't open file '/home/ccor/train.py': [Errno 2] No such file or directory
E1127 23:09:19.158000 140218904396800 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 4060931) of binary: /home/ccor/.conda/envs/captum_test/bin/python
Traceback (most recent call last):
  File "/home/ccor/.conda/envs/captum_test/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-11-27_23:09:19
  host      : cn11.hpc.itu.dk
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 4060932)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-27_23:09:19
  host      : cn11.hpc.itu.dk
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 4060931)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
