cn11.hpc.itu.dk
Monitoring_GPUs_on_HPC
ResearchProject
captum_test.job
captum_test.png
captum_test.py
hpc_saliency_test.py
logs
neuralcoref
qaskills
qatest.job
requirements.txt
saliency_test.csv
saliency_test2.tsv
simple.job
stupid.py
test.job
W1127 23:34:36.943000 140180618273792 torch/distributed/run.py:779] 
W1127 23:34:36.943000 140180618273792 torch/distributed/run.py:779] *****************************************
W1127 23:34:36.943000 140180618273792 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1127 23:34:36.943000 140180618273792 torch/distributed/run.py:779] *****************************************
2024-11-27 23:34:44.957	cn11.hpc.itu.dk:0	train:380	INFO	CLI environment prepared
2024-11-27 23:34:44.962	cn11.hpc.itu.dk:1	olmo.util:165	CRITICAL	Uncaught FileNotFoundError: [Errno 2] No such file or directory: '/home/ccor/--config'
Traceback (most recent call last):
  File "/home/ccor/ResearchProject/train.py", line 389, in <module>
    cfg = TrainConfig.load(yaml_path, [clean_opt(s) for s in args_list])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/olmo/config.py", line 138, in load
    raw = om.load(str(path))
          ^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ccor/--config'
2024-11-27 23:34:44.969	cn11.hpc.itu.dk:0	olmo.util:165	CRITICAL	Uncaught FileNotFoundError: [Errno 2] No such file or directory: '/home/ccor/--config'
Traceback (most recent call last):
  File "/home/ccor/ResearchProject/train.py", line 389, in <module>
    cfg = TrainConfig.load(yaml_path, [clean_opt(s) for s in args_list])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/olmo/config.py", line 138, in load
    raw = om.load(str(path))
          ^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ccor/--config'
[rank0]:[W1127 23:34:45.593568258 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W1127 23:34:46.363000 140180618273792 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 4061342 closing signal SIGTERM
E1127 23:34:46.477000 140180618273792 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 4061341) of binary: /home/ccor/.conda/envs/captum_test/bin/python
Traceback (most recent call last):
  File "/home/ccor/.conda/envs/captum_test/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
ResearchProject/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-27_23:34:46
  host      : cn11.hpc.itu.dk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4061341)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
