cn11.hpc.itu.dk
Monitoring_GPUs_on_HPC
ResearchProject
captum_test.job
captum_test.png
captum_test.py
hpc_saliency_test.py
logs
neuralcoref
qaskills
qatest.job
requirements.txt
saliency_test.csv
saliency_test2.tsv
simple.job
stupid.py
test.job
W1127 23:28:00.973000 140618809365504 torch/distributed/run.py:779] 
W1127 23:28:00.973000 140618809365504 torch/distributed/run.py:779] *****************************************
W1127 23:28:00.973000 140618809365504 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1127 23:28:00.973000 140618809365504 torch/distributed/run.py:779] *****************************************
Traceback (most recent call last):
  File "/home/ccor/ResearchProject/train.py", line 26, in <module>
    from olmo.eval import build_evaluators
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/olmo/eval/__init__.py", line 5, in <module>
Traceback (most recent call last):
  File "/home/ccor/ResearchProject/train.py", line 26, in <module>
    from olmo.eval import build_evaluators
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/olmo/eval/__init__.py", line 5, in <module>
    from torchmetrics import MeanMetric, Metric
ModuleNotFoundError: No module named 'torchmetrics'
    from torchmetrics import MeanMetric, Metric
ModuleNotFoundError: No module named 'torchmetrics'
E1127 23:28:12.998000 140618809365504 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 4061182) of binary: /home/ccor/.conda/envs/captum_test/bin/python
Traceback (most recent call last):
  File "/home/ccor/.conda/envs/captum_test/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/captum_test/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
ResearchProject/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-11-27_23:28:12
  host      : cn11.hpc.itu.dk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4061183)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-27_23:28:12
  host      : cn11.hpc.itu.dk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4061182)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
